### ISSUE TITLE
Stratagies for moving playhead in time with AKSequencer?

### ISSUE THREAD

**Issue by maksutovic** [cemolcay/MIDITimeTableView#10]
Hi Cemoclay,

Really loving this library!! So Far i'm able to populate with custom cells and everything is going well. I have a AKSequencer hooked up as well, but for the life of me I can't figure out how to get the playhead to play back smoothly like you have in ChordBud. ANY guidance would be so appreciative!

**Comment by cemolcay** [comment]
Hi, thanks! In ChordBud, I added a timer with an interval of `1 / tempo.bpm` and I just set the MIDITimeTableView's playhead `position` to AKSequencer's `sequencer.currentRelativePosition.beats`.

**Comment by maksutovic** [comment]
Works perfectly, thank you, I owe you some Raki! What delegate should I work with if I want to scroll the whole timeTable once the playhead has reached the edge of the screen? `MIDITimeTablePlayheadViewDelegate` ?

**Comment by cemolcay** [comment]
Well, it don't support an auto-scrolling feature for playhead but, playhead's position is a dynamic property which you can listen its value changes with KVO.

``` swift
@objc public dynamic var position: Double = 0.0
```

I think you could set the parent scroll view's `contentOffset.x` by calculating the playhead position in KVO handler. And, yeah rakı would be nice, Şerefe! 😄

**Comment by maksutovic** [comment]
So sorry, I got it working! Thanks so much, loving this library , Raki on the way ;)
